### ISSUE TITLE
How can I show popper grammatically? 

### ISSUE THREAD

**Issue by mishokupatadze** [RobinCK/vue-popper#109]
First of all, awesome plugin! It really fits my requirements and helps a lot.

I need to show/hide popup programmatically without DOM manipulations (should be based on router change). Is it possible? If yes how?

**Comment by MaraSerj** [comment]
For me it works:
`<popper ref="popperRef" trigger="click"></popper>` - html
`this.$refs.popperRef.showPopper = true` - to show
`this.$refs.popperRef.showPopper = false` - to hide

**Comment by RobinCK** [comment]
`force-show` prop

```<popper ref="popperRef" trigger="click" force-show="true"></popper>```
