### ISSUE TITLE
Focus and blur listener is conflict with 'hover' trigger mode

### ISSUE THREAD

**Issue by vq0599** [RobinCK/vue-popper#114]
Hi,
When using hover mode, If the  popper content  includes a link `<a href="#">click me</a>` and reference element is focus,  the link can't be clicked because the blur event will close the popper firstly.

This is a example https://jsfiddle.net/aLuroykm/4/

See https://github.com/RobinCK/vue-popper/pull/48. Why not add a new trigger mode 'focus' ? 

Thanks for your awesome plugin.

**Comment by RobinCK** [comment]
example works fine https://monosnap.com/file/2tQkh3J0yVEC5JSdayeD8pBO6mBpvS

**Comment by vq0599** [comment]
Sorry, Perhaps I have not expressed myself very well. 

1. It's ok.
![Aug-27-2019 15-42-59](https://user-images.githubusercontent.com/20247366/63751200-70f7de00-c8e1-11e9-8cfa-b3529e4d959a.gif)

2. The link unable be clicked, because blur event be triggered before click event.
![Aug-27-2019 15-43-08](https://user-images.githubusercontent.com/20247366/63751160-5faed180-c8e1-11e9-945c-1f8adb2188a5.gif)

**Comment by RobinCK** [comment]
unfortunately, I don’t have time to edit the component itself, but the problem can be solved somehow https://jsfiddle.net/3qsac2up/3/

**Comment by vq0599** [comment]
Thanks.
How about adding a new trigger mode 'focus' and removing focus and blur listener on 'hover' mode?
Refer https://ant.design/components/tooltip/
Can I submit a PR?

```js
      switch (this.trigger) {
        case 'click':
          on(this.referenceElm, 'click', this.doToggle);
          on(document, 'click', this.handleDocumentClick);
          break;
        case 'hover':
          on(this.referenceElm, 'mouseover', this.onMouseOver);
          on(this.popper, 'mouseover', this.onMouseOver);
          on(this.referenceElm, 'mouseout', this.onMouseOut);
          on(this.popper, 'mouseout', this.onMouseOut);
          break;
        case 'focus':
          on(this.referenceElm, 'focus', this.onMouseOver);
          on(this.popper, 'focus', this.onMouseOver);
          on(this.referenceElm, 'blur', this.onMouseOut);
          on(this.popper, 'blur', this.onMouseOut);
      }
```

**Comment by RobinCK** [comment]
Yes you can do PR

**Comment by ouba421** [comment]
![image](https://user-images.githubusercontent.com/31402685/66694356-0c53df80-ece5-11e9-9d1f-36fb25e71c1d.png)

**Comment by ouba421** [comment]
Click on the popup and close the popover!
![image](https://user-images.githubusercontent.com/31402685/66694377-37d6ca00-ece5-11e9-862b-6a73228d59b7.png)
![image](https://user-images.githubusercontent.com/31402685/66694380-3b6a5100-ece5-11e9-9c47-9af4fc1ebfdb.png)
![image](https://user-images.githubusercontent.com/31402685/66694382-3e654180-ece5-11e9-9e93-52c18107781c.png)
