### ISSUE TITLE
Popper v2

### ISSUE THREAD

**Issue by the94air** [RobinCK/vue-popper#127]
Can we have support for Popper v2 as of the current package only support Popper v1.15.0

**Comment by pdevito3** [comment]
really should be updated to v2. Is this on the roadmap at all?

**Comment by the94air** [comment]
I don't think so. I doubt if it's maintained anymore. I ended up using the original library anyway ¯\_(ツ)_/¯. And I think I like that I did that.

**Comment by RobinCK** [comment]
I don't see any advantages in the new version popperjs
Anyway you can do PR

**Comment by atomiks** [comment]
> I don't see any advantages in the new version popperjs

?

It's 1.5 kB smaller by default & tree-shakable, [38 bugs were fixed](https://github.com/popperjs/popper-core/issues?q=is%3Aissue+is%3Aclosed+label%3A%22Fixed+in+v2%22), the default behavior is far more intuitive, offsets rounding is more accurate with no blurry issues, the API far is cleaner and easier to use (modifier merging by name, adheres better to HTML spec), plus some useful features added.

**Comment by curtisbelt** [comment]
Would appreciate testing and feedback here! https://github.com/RobinCK/vue-popper/pull/133
