### ISSUE TITLE
Updating text of centered tooltip doesn't update the tooltip position

### ISSUE THREAD

**Issue by maxpaj** [RobinCK/vue-popper#13]
I just stumbled upon this problem.

I was however able to solve it by setting a `ref="someName"` attribute on the `<popper>` and then using `$refs.someName.popperJS.update()` manually.

Here's a JSFiddle. Try clicking the "bottom" link:
https://jsfiddle.net/maxpaj/9qvmn093/

**Comment by RobinCK** [comment]
Hi @maxpaj 
Sorry for a long time did not answer, did not quite understand what the problem is

**Comment by maxpaj** [comment]
If a tooltip has it's contents (text for example) updated while it is being displayed and the tooltip is configured to be centered, it won't be centered after the content changes.

So it looks like this, a centered tooltip below `ref`:

```
              ref
        _______________
        |    test     |
        ¨¨¨¨¨¨¨¨¨¨¨¨¨¨¨
```

Then after changing the content, not centered below `ref` anymore:

```
              ref
        _________________________________
        |    test with more content     |
        ¨¨¨¨¨¨¨¨¨¨¨¨¨¨¨¨¨¨¨¨¨¨¨¨¨¨¨¨¨¨¨¨¨
```

Then if you drag away the mouse so the tooltip is hidden and then make it appear again, it will have adjusted:

```
              ref
_________________________________
|    test with more content     |
¨¨¨¨¨¨¨¨¨¨¨¨¨¨¨¨¨¨¨¨¨¨¨¨¨¨¨¨¨¨¨¨¨
```

**Comment by RobinCK** [comment]
thanks
