### ISSUE TITLE
How to call event hide?

### ISSUE THREAD

**Issue by Venegrad** [RobinCK/vue-popper#142]
Hi i cant find docs how to call event hide?

**Comment by ilya-buligin** [comment]
> Hi i cant find docs how to call event hide?

You can make something like this:
`
<Popper ref="popper">...</Popper>
...
this.$refs.popper.doClose()
`
Be careful - `doClose` is an internal method of vue-popper. Better use forceShow property ;)

**Comment by Venegrad** [comment]
im already leave this plugin, cuz its not working correctly,,, Using clean popper.js with api.
