### ISSUE TITLE
Code not added to dist file but is added to src file

### ISSUE THREAD

**Issue by denniszon** [RobinCK/vue-popper#16]
See this ticket with the old PR: https://github.com/RobinCK/vue-popper/issues/14

The following code is never added in the dist files, only to the src files.

```
        if (this.appendToBody) {
          document.body.removeChild(this.popper.parentElement);
        }
```

I have made a PR for you: https://github.com/RobinCK/vue-popper/pull/17

**Comment by RobinCK** [comment]
Merged
