### ISSUE TITLE
Allow both Hover and click trigger at the same time

### ISSUE THREAD

**Issue by DylanC** [RobinCK/vue-popper#20]
It would be great to have **both** hover and click as options instead of choosing one **or** the other.

**Comment by RobinCK** [comment]
Hi 
We can not click without hovering the mouse
For this, there is a force-show with which you can organize your logic

**Comment by DylanC** [comment]
@RobinCK - I mean't like in Bootstrap you can do click on mobile and hover works on desktop. (without changing any code)

**Comment by karakum** [comment]
@RobinCK 
I join the question.
Now you have to manually process clicks on mobile devices (no mouse) when the `hover` mode selected.
It would be easier if you could specify `click, hover`
On desktop if you got `click` after `hover` - just toggle state. On mobile there is only `click` events.
