### ISSUE TITLE
Target multiple components inside Popper - currently only works with single instance

### ISSUE THREAD

**Issue by chrisdel101** [RobinCK/vue-popper#25]
I have a button component inside the popper component. Now, only the first button gets a `reference` but I need all the buttons in the loop to have this. How can I make all the buttons respond to popover?
vhs-button is a custom child component below. 

<template>
<div class="outer-div">

    <popper trigger="click" :options="{placement: 'top'}" ref="popOv" v-for="(option, i) in data">
      <div class="popper">
        Test Text
      </div>

     //multiple buttons` here
      <vhs-button slot="reference" :propsData="option" />
      
    </popper>
</div>
</template>

I have multiple choices, and true\falses, that need to show the feedback with a popover and there is always more than one button. It's working otherwise.
If this doesn't make sense I'll try to make a pen for it.

**Comment by RobinCK** [comment]
Hi @chrisdel101 
Please create example in jsfiddle.net
Thanks

**Comment by chrisdel101** [comment]
This question was a non-starter. I tried to loop over the poppers and it did not work. Now it does. I must have had a syntax error. Being a junior dev this common. Below is what is working: 
```

<div class="question-options">

    <popper v-for="(option, i) in data" trigger="click" :options="{placement: 'top'}" ref="popOv" :disabled="disablePO" v-bind:key="i">
      <div class="popper">
        {{feedback}}
      </div>
      <vhs-button v-bind:key="i" slot="reference" ref="btn" :class="{'disabled': isComplete}" v-bind:text=option.displayName v-bind:icon=option.icon @click.native="check(option, $event),componentFirstClick()" @mousedown.native="disablePopover(), feedbackTrue()" @focusout.native="feedbackTrue()" />
    </popper>
  </div>

```
