### ISSUE TITLE
Is it possible to attach the popper by using element ID or getBoundingClientRect as reference?

### ISSUE THREAD

**Issue by weislanes** [RobinCK/vue-popper#4]
I want to bind the popper component to an element not defined in the component. 

Popper.js achieves this by using  element by ID or getBoundingClientRect. Is this possible with vue-popper? 

So essentially, the component is the popper only and the user decides what to attach it to without having to include the reference in the  component. 

Great work btw

**Comment by RobinCK** [comment]
In the near future I will make a directive for such tasks.

**Comment by weislanes** [comment]
That would be super useful! Thank you.

**Comment by Narretz** [comment]
Was this ever included?

**Comment by RobinCK** [comment]
I think it suits you https://github.com/hekigan/vue-directive-tooltip
