### ISSUE TITLE
When parent container has overflow set, popper positioning screws up

### ISSUE THREAD

**Issue by danchristian** [RobinCK/vue-popper#42]
When the parent container has `overflow: auto` or `overflow: scroll` set, the placement of the poppers is incorrect.

https://jsfiddle.net/ec4o2wt0/

How can I fix this? 

I see a similar issue here perhaps https://github.com/FezVrasta/popper.js/issues/248

**Comment by danchristian** [comment]
After seeing [this issue,](https://github.com/bootstrap-vue/bootstrap-vue/issues/1851), I have tried `popper(trigger="click", boundaries-selector="viewport")` but the problem still persists.

**Comment by danchristian** [comment]
After a search around, I saw a [similar issue](https://github.com/atomiks/tippyjs/issues/196#issuecomment-371635364) on tippy.js (which uses popper.js) and worked out how to solve this:			

`popper(trigger="click",  :options="{ modifiers: { preventOverflow: {escapeWithReference: true}}}")`

**Comment by RobinCK** [comment]
@danchristian thanks

**Comment by voodoocode** [comment]
I want to add up on @danchristian solution, by noting that I only got that working by also using: 
`:append-to-body="true"`
