### ISSUE TITLE
How do I execute the show method from code

### ISSUE THREAD

**Issue by jcifuentes91** [RobinCK/vue-popper#43]
This is more a question, rather than a bug, I would like to trigger the show event, I tried this 
`` <popper trigger="click" :options="{placement: 'bottom'}" ref="searchpop" >... </popper> `` and on the parent 
``this.$refs.searchpop.doShow();`` and nothing happens. Also tried ``this.$refs.searchpop.$emit("show");``

**Comment by RobinCK** [comment]
You need 
force-show prop

```
<popper trigger="click" :force-show="true" >... </popper>
// or

<popper trigger="click" :force-show="yourShowState" >... </popper>
<button @click="yourShowState = !yourShowState">show/hide</button>
```
