### ISSUE TITLE
Show on click and hide on focus out

### ISSUE THREAD

**Issue by mohinithorat** [RobinCK/vue-popper#44]
The tool tip pop up should  get minimized when the user clicks out or scrolls the screen.

How to do that with this plugin?

**Comment by RobinCK** [comment]
I think you can manipulate prop force-show

**Comment by mohinithorat** [comment]
I tried using force-show, but it doesn't work as intended. I want popup to be displayed on 'click' event and make it hidden on mouseout from popup or  clicked element.

**Comment by RobinCK** [comment]
this specific implementation you need to implement yourself using force-show

**Comment by mohinithorat** [comment]
I tried one implementation, 
In node_modules\vue-popperjs\dist\js/vue-popper.js, 
I modified the file to add on(this.popper, 'mouseout', this.onMouseOut);  
This fulfills my requirement but I cannot modify the core file as this will be the temporary implementation as on npm install/update this change won't be there.
Is there a way I can modify it in my component?

**Comment by f0rx** [comment]
Add a scroll listener on the element/window (with overflow:scroll/auto) and put - `this.$child.showPopper = false;` in it.
Whenever the window/element is scrolled, the value of `showPopper` will be set to false and this should hide the `<popper></popper>` component.
