### ISSUE TITLE
https://unpkg.com/vue-popperjs is broken

### ISSUE THREAD

**Issue by GeoffroyR** [RobinCK/vue-popper#74]
Cannot find "/index.js" in vue-popperjs@1.6.2

**Comment by RobinCK** [comment]
this bug unpkg.com

please use 
https://unpkg.com/vue-popperjs@1.6.2/dist/js/vue-popper.min.js

**Comment by RobinCK** [comment]
unpkg issue https://github.com/unpkg/unpkg.com/issues/156
