### ISSUE TITLE
Problem with Radio-Button

### ISSUE THREAD

**Issue by kamrava** [RobinCK/vue-popper#8]
When I use this great package with Radio-Button. It has a problem. When you click on label it keeps hiding!
You can check that here: [JSFiddle](https://jsfiddle.net/3oxhsunm/3/)

Any idea would be great appreciated.

**Comment by RobinCK** [comment]
@kamrava hello, thanks!

Maybe you need to use trigger hover https://jsfiddle.net/9kb0x80d/ or use force-show https://jsfiddle.net/9kb0x80d/1/ for your specific logic

**Comment by kamrava** [comment]
Thank you. It's works.

But is there any way to do this without using `force-show` ?

**Comment by RobinCK** [comment]
Force-show is added specifically for the ability to more flexibly configure the popper display when click and hover does not match

**Comment by kamrava** [comment]
The only problem with this way is that I want to popper window disappears when I click outside of popper window. But with `force-show` It can't :(

**Comment by RobinCK** [comment]
hover trigger?

**Comment by RobinCK** [comment]
@kamrava https://jsfiddle.net/c0kq7g75/ example

**Comment by kamrava** [comment]
@RobinCK No, I need click trigger.

**Comment by RobinCK** [comment]
The problem is that clicking on a label causes a click on the input, because this popper disappears. I do not see any solutions
