### ISSUE TITLE
Popper stuck on page when reference disappears

### ISSUE THREAD

**Issue by Alsciende** [RobinCK/vue-popper#9]
I have a link as a reference inside a on-hover popper. When the user clicks the link, the component is replaced. When that happens, the popper stays on the page and cannot be removed.

```
<template>
    <popper trigger="hover" :visible-arrow="true" :append-to-body="true">
        <div class="popper">
            <my-tooltip-component></my-tooltip-component>
        </div>

        <router-link slot="reference" :to="somewhere-else">Link</router-link>
    </popper>
</template>
```

I fixed it by wrapping the link inside `<span slot="reference" v-on:click.capture="hidePopper"></span>` and by setting `popper.disabled=true` inside `hidePopper()`, but I think it would be better for vue-popperjs to catch the event that the reference is removed and to destroy the tooltip.

Thank you for your time and effort!

**Comment by RobinCK** [comment]
perhaps you will be helped by a similar solution # 11 and instead of router-lint
method () {
     router.push ({path: 'home'})
     this.show = false
}
