### ISSUE TITLE
IE9 Syntax Error

### ISSUE THREAD

**Issue by ftes** [RobinCK/vue-popper#90]
Version 1.x can be bundled with webpack and works in IE9.

Version 2.x leads to a `SyntaxError` in IE9. Unfortunately my IE9 refuses to tell me in what line the error occurs.

Workaround: Transpile it. If using `vue-cli` add this to your `vue.config.js`:

  ```
// vue-popperjs >=2.0.0 is not compatible with IE9 (SyntaxError). Must be transpiled.
  transpileDependencies: ["vue-popperjs"],
```

**Comment by RobinCK** [comment]
If you need IE9, use the 1.x version.
2.x only IE11+ 

In fact, nothing has changed between 1.x and 2.x
assembly method only
