### ISSUE TITLE
Output produced in dist is not es5 compatible

### ISSUE THREAD

**Issue by andriy-f** [RobinCK/vue-popper#91]

**Comment by RobinCK** [comment]
if you need support IE (es5) use 1.x.x version
Modern browser supported es6

**Comment by andriy-f** [comment]
@RobinCK Does 1.x.x receive backports of fixes for 2.x?
BTW I have played with rollup config a bit. Adding 

```
babel({
      ...
      extensions: ['.js', '.jsx', '.es6', '.es', '.mjs', '.vue'],
})
```
It helped a bit (replaced some cost with var but not all)

**Comment by RobinCK** [comment]
I see no reason to support IE in 2019, hence
vue-popper and vue-gallery used es6+ syntax

there is no difference between 1.x and 2.x.
In essence, only the build has changed.
