### ISSUE TITLE
Issue Using StopPropagation

### ISSUE THREAD

**Issue by mahendrushivam** [RobinCK/vue-popper#98]
when using stopPropagation on slot reference element stoping teh other poppers from closing that has stopPropagation

`<popper
    placement="right"
    :stopPropagation="true"
    trigger="click">
    <div class="p-4"> How are you </div>
    <button type="primary" slot="reference">
        Open slot
    </button>
    </popper>`

`<popper
    placement="right"
    :stopPropagation="true"
    trigger="click">
    <div class="p-4"> I am Fine </div>
    <button type="primary" slot="reference">
        Open sAnother slot
    </button>
    </popper>`

**Comment by RobinCK** [comment]
#116
